filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/samples/*.log 
    json:
      keys_under_root: true

setup.ilm.enabled: false
setup.template.enabled: false

output.elasticsearch:
  hosts: ["http://es01:9200"]
  index: "sample-%{[agent.version]}-%{+yyyy.MM}"

setup.kibana:
  host: "http://kibana:5601"